source: app
destination: dist

encoding: utf-8
permalink: pretty
paginate: 5
paginate_path: page/:num

markdown: kramdown
kramdown:
  input: GFM

include:
  - CNAME

include:
  - CNAME

exclude:
  - styles
  - scripts
  - images

timezone: Australia/Melbourne

title: Andy Stanford-Bluntish
description: I build things on the web. I love what I do.
url: http://andybluntish.com
est: 2006
ga: UA-26537336-1

author:
  name: Andy Stanford-Bluntish
  email: andy@bluntish.net
  role: web developer
  username: andybluntish
  location:
    country: Australia
    region:
      name: Victoria
      abbr: VIC
    city: Melbourne

defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: pages
    values:
      layout: page
