source: app
destination: dist

encoding: utf-8
permalink: pretty
paginate: 10
paginate_path: page/:num

markdown: kramdown
kramdown:
  input: GFM

include:
  - CNAME

# Assets compilation is handled by Gulp
exclude:
  - css
  - js
  - img
  - apple-touch-icon-precomposed.png
  - favicon.ico

# Don't clobber asset files during rebuild
keep_files:
  - css
  - js
  - img
  - apple-touch-icon-precomposed.png
  - favicon.ico

defaults:
  - scope:
      type: posts
    values:
      layout: post
      type: post
  - scope:
      type: pages
    values:
      layout: page
      type: page

timezone: Australia/Melbourne

title: Andy Stanford-Bluntish
description: I build things on the web. I love what I do.
url: http://andybluntish.com
est: 2006
ga: UA-26537336-1

author:
  name: Andy Stanford-Bluntish
  email: andy@bluntish.net
  role: web developer and designer
  username: andybluntish
  location:
    country: Australia
    region:
      name: Victoria
      abbr: VIC
    city: Melbourne
